name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/p/premium-bond-checker
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
    - name: Install pip dependencies
      run: poetry install
    - name: Package
      run: |
        poetry version ${{ github.event.release.tag_name }}
        poetry build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4
